"""The post's matplotlib base: shared labels, colors and panel drawers.

`make_results_figs.py` and `make_forecast_figs.py` are the matplotlib twins of
the Plotly figures, and this is what they draw with. It exists so the post
renders from a clone of this repository alone: the memo is a separate local
deliverable and is not tracked, so a figure script that imported it could not
be regenerated by anyone but its author.

Nothing here is post-specific styling for its own sake. Colors come from
`viz.core` and axis names from `config.AXIS_TITLES`, the same two sources the
dashboard reads, so the post cannot name an axis or color a series differently
from the cards.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.dates as mdates  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO))

from multiaxis_eci.analysis import mirt_model_timeline_df  # noqa: E402
from multiaxis_eci.config import AXIS_TITLES  # noqa: E402
from multiaxis_eci.viz.core import (AI_COLOR, FUTURE_COLOR, HUMAN_COLOR,  # noqa: E402
                                    PASSED_COLOR)

__all__ = ["AI_COLOR", "HUMAN_COLOR", "PASSED_COLOR", "FUTURE_COLOR",
           "AXIS_TITLES", "FOREST_FRONTIER", "pretty",
           "timeline_forecast_panel", "loadings_axes", "axis_timelines"]

TREND_COLOR = "#ff9500"

# Frontier releases pinned into every forest whatever their posterior SD: a
# frontier model is the headline of the figure, so a wide interval is drawn
# rather than the row dropped.
FOREST_FRONTIER = {"claude-mythos-preview-early", "claude-fable-5",
                   "gpt-5.6-sol_max"}

# Vendor tokens whose casing a naive .title() would mangle.
_CASE = {"gpt": "GPT", "glm": "GLM", "o1": "o1", "o3": "o3", "o4": "o4",
         "ai": "AI", "xhigh": "xhigh", "xh": "xhigh", "sol": "Sol",
         "minimax": "MiniMax", "deepseek": "DeepSeek", "terra": "Terra"}


def pretty(raw: str) -> str:
    """Readable label for a raw model id: effort suffix in parentheses, date
    suffixes dropped, vendor casing fixed. Human tiers pass through as-is."""
    name, *effort = raw.split("_", 1)
    name = re.sub(r"-\d{4}-\d{2}(-\d{2})?$", "", name)   # trailing release date
    toks = [_CASE.get(t, t.capitalize() if t.isalpha() else t)
            for t in name.split("-")]
    label = " ".join(toks)
    if effort:
        e = effort[0].replace("_", " ")
        label += f" ({_CASE.get(e, e)})"
    return label


def timeline_forecast_panel(ax, tl: pd.DataFrame, hstat: pd.DataFrame, fc,
                            title: str, today: pd.Timestamp,
                            show_ylabel: bool) -> None:
    """One per-axis ability timeline with the frontier trend overlaid."""
    # All dated models as a faint cloud (context).
    ax.scatter(pd.to_datetime(tl["release_date"]), tl["mean"], s=10,
               color=AI_COLOR, alpha=0.30, edgecolors="none", zorder=1)

    # Human tier levels as faint reference lines (detail lives in the crossover
    # figure; here they only show what the trend is heading toward).
    for _, r in hstat.iterrows():
        ax.axhline(r["mean"], color=HUMAN_COLOR, ls="--", lw=0.7, alpha=0.45,
                   zorder=0)

    # Trend: median line + the forecast band (hdi_prob from FORECAST_KW).
    gx = pd.to_datetime(fc.grid_dates)
    ax.fill_between(gx, fc.lo, fc.hi, color=TREND_COLOR, alpha=0.15, zorder=2)
    ax.plot(gx, fc.median, color=TREND_COLOR, ls="--", lw=2.2, zorder=3,
            label="frontier trend (80% band)")

    ax.axvline(today, color="#444", ls=":", lw=1, zorder=2)
    ax.set_title(title, fontsize=10)
    if show_ylabel:
        ax.set_ylabel("ability (aligned axis scale)")
    ax.xaxis.set_major_locator(mdates.YearLocator(base=2))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    ax.tick_params(axis="x", labelsize=8)
    ax.grid(axis="y", color="0.93", lw=0.6)


def loadings_axes(view, data, out: Path, top_n: int = 20) -> Path:
    """The benchmarks that define each axis, by axis SHARE.

    A loading conflates two things, how steep a benchmark is overall (the length
    of its loading row) and how much of that steepness points along this axis.
    Ranking by raw loading therefore names an axis after its steepest rows, and a
    long half-aligned row out-ranks a short row pointing squarely along the axis.
    The dashboard ranks by share instead, `med^2 / sum_k med^2`, the fraction of
    the squared row norm on this axis, and so does this figure. The bar is still
    the loading, so strength stays visible; the number at the right is the share.
    """
    A = view.require_A()                          # (S, B, K)
    bench = data.blookup.sort_values("benchmark_idx")["benchmark"].tolist()
    med = np.median(A, axis=0)
    lo, hi = np.percentile(A, [2.5, 97.5], axis=0)
    share = med ** 2 / np.maximum((med ** 2).sum(axis=1, keepdims=True), 1e-12)

    fig, axes = plt.subplots(1, view.K, figsize=(17, 7.2))
    for k, ax in enumerate(np.atleast_1d(axes)):
        order = np.argsort(-share[:, k])[:top_n]
        ys = np.arange(len(order))[::-1]
        for y, b in zip(ys, order):
            col = AI_COLOR if med[b, k] >= 0 else "#d62728"
            ax.barh(y, med[b, k], color=col, height=0.72)
            ax.plot([lo[b, k], hi[b, k]], [y, y], color="#555", lw=0.9)
        ax.set_yticks(ys)
        ax.set_yticklabels([bench[b] for b in order], fontsize=8)
        ax.axvline(0, color="#222", lw=0.8)
        ax.set_title(AXIS_TITLES.get(view.names[k], view.names[k]), fontsize=10)
        ax.set_xlabel("loading (median, 95%)")
        ax.grid(axis="x", color="0.92", lw=0.6)
        # share printed in a right-hand gutter, so a pure short row reads as
        # pure even though its bar is short
        x0, x1 = ax.get_xlim()
        ax.set_xlim(x0, x1 + 0.30 * (x1 - x0))
        for y, b in zip(ys, order):
            ax.text(1.0, y, f"{share[b, k]:.2f}",
                    transform=ax.get_yaxis_transform(),
                    ha="right", va="center", fontsize=7, color="#555")
        ax.text(1.0, len(order) - 0.2, "share",
                transform=ax.get_yaxis_transform(), ha="right", va="center",
                fontsize=7.5, color="#222")
    fig.suptitle(f"The {top_n} benchmarks that define each axis, "
                 "ranked by axis share", fontsize=12)
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {out}")
    return out


def axis_timelines(view, data, raw, out: Path) -> Path:
    """Per-axis ability over release date, all dated models (mean, 95% HDI)."""
    fig, axes = plt.subplots(1, view.K, figsize=(16, 5.2))
    for k, ax in enumerate(np.atleast_1d(axes)):
        tl = mirt_model_timeline_df(view.theta, k, data, raw,
                                    sd_cap=None, drop_low_obs=False)
        x = pd.to_datetime(tl["release_date"])
        ax.vlines(x, tl["hdi_low"], tl["hdi_high"], color=AI_COLOR,
                  lw=0.7, alpha=0.35, zorder=1)
        ax.scatter(x, tl["mean"], s=12, color=AI_COLOR, alpha=0.65,
                   edgecolors="none", zorder=2)
        ax.set_title(AXIS_TITLES.get(view.names[k], view.names[k]), fontsize=10)
        ax.set_xlabel("Release date")
        if k == 0:
            ax.set_ylabel("ability (mean, 95% HDI)")
        ax.xaxis.set_major_locator(mdates.YearLocator())
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
        ax.grid(color="0.93", lw=0.6)
    fig.suptitle("Per-axis abilities over time (all dated models)", fontsize=12)
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {out}")
    return out
